name: grassh_renew
description: "A simple ssh client."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: 3.22.3

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Twemoji
      fonts:
        - asset: assets/fonts/Twemoji.Mozilla.ttf
    - family: Codicon
      fonts:
        - asset: assets/fonts/Codicon.ttf
